---
title: "Evidence Synthesis (Meta, Meta Analysis)"
author: "Nathan Hall"
date: '`r Sys.Date()`'
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead{}
  - \fancyfoot[LE,RO]{\thepage}
  - \renewcommand{\headrulewidth}{0.4pt}
  - \renewcommand{\footrulewidth}{0.4pt}
  - \fancyfoot[CO,CE]{OhdsiShinyModules Package Version `r  utils::packageVersion("OhdsiShinyModules")`}
output:
  html_document:
    number_sections: yes
    toc: yes
  word_document:
    toc: yes
  pdf_document:
    includes:
      in_header: preamble.tex
    number_sections: yes
    toc: yes
---

```{=html}
<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{EvidenceSynthesis}
-->
```
```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Meta-analysis plays a pivotal role in healthcare research by enabling the synthesis of findings from multiple studies to draw more generalizable conclusions. In the context of distributed health data networks, where data are spread across various sites with diverse populations and practices, synthesizing evidence becomes both a challenge and a necessity. The [EvidenceSynthesis](https://github.com/OHDSI/EvidenceSynthesis "EvidenceSynthesis") R package addresses these challenges head-on. It offers a suite of tools designed for combining causal effect estimates and study diagnostics from multiple data sites, all while adhering to stringent patient privacy requirements and navigating the complexities inherent to observational data. This approach enhances the robustness of meta-analytical conclusions and extends the utility of distributed health data for research purposes.

# Features and Functionalities

The Meta module which utilizes the EvidenceSynthesis R package makes use of the following features to summarize the results of a study:

1.  **Meta-Analysis Methods**: Facilitates both traditional fixed-effects and random-effects meta-analyses, accommodating studies with different degrees of between-site or between-database variability.
2.  **Forest Plot Generation**: Provides capabilities for creating forest plots, visual summaries that illustrate the effects estimated by individual studies, their confidence intervals, and the synthesized overall effect.
3.  **Non-Normal Likelihood Approximations**:  Utilizes non-normal approximations for the per-data-site likelihood function to reduce bias in scenarios with small or zero counts, a frequent issue in distributed research environments.

The syntheses are generated for both Cohort Method and Self-Controlled Case Series estimation results from the study, providing both information on the diagnostic results within each database and the visualized and tabular results of the meta analysis.

# Utility and Application

The EvidenceSynthesis package is instrumental in synthesizing evidence from observational studies across multiple healthcare databases. Its significance is underscored in scenarios characterized by:

**Comparative Effectiveness Research**: Synthesizing evidence from disparate sources allows for stronger, more reliable comparisons of treatment outcomes, enriching the foundation for clinical decision-making.

**Safety Surveillance**: Aggregated safety data across databases enhance the detection and understanding of adverse drug reactions, contributing to safer patient care.

**Policy and Clinical Guidelines Development**: Meta-analytical findings informed by comprehensive, real-world data can guide policy formulation and the updating of clinical guidelines, ensuring they are grounded in broad-based evidence.

**Addressing Challenges of Small Sample Sizes**: The EvidenceSynthesis package notably advances the field by tackling the issue of small sample sizes and zero event counts, which traditional meta-analytical methods often handle poorly. Its innovative use of non-normal likelihood approximations enables more precise effect size estimation under such conditions, ensuring that the insights derived from meta-analyses are both accurate and meaningful. This attribute is particularly beneficial in distributed health data networks, where individual site/database data may be limited but collectively hold significant informational value.
