---
title: "Self-Controlled Case Series"
author: "Nathan Hall"
date: '`r Sys.Date()`'
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead{}
  - \fancyfoot[LE,RO]{\thepage}
  - \renewcommand{\headrulewidth}{0.4pt}
  - \renewcommand{\footrulewidth}{0.4pt}
  - \fancyfoot[CO,CE]{OhdsiShinyModules Package Version `r  utils::packageVersion("OhdsiShinyModules")`}
output:
  html_document:
    number_sections: yes
    toc: yes
  word_document:
    toc: yes
  pdf_document:
    includes:
      in_header: preamble.tex
    number_sections: yes
    toc: yes
---

```{=html}
<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Self-Controlled Case Series}
-->
```
```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The Self-Controlled Case Series (SCCS) method offers a nuanced approach to investigating the relationship between exposures and outcomes within individual patients over time. SCCS designs are particularly adept at comparing the rate of outcomes during times of exposure to rates during periods of non-exposure, including before, between, and after exposure episodes. By leveraging a Poisson regression that is conditioned on the individual, the SCCS design inherently addresses the question: “Given that a patient has the outcome, is the outcome more likely to occur during exposed time compared to non-exposed time?” The design choices outlined in the method are pivotal for defining an SCCS question, with each choice playing a critical role in the study's design and outcomes:

**Target Cohort**: This represents the treatment under investigation.
**Outcome Cohort**: This cohort signifies the outcome of interest.
**Time-at-Risk**: Identifies the specific times when the risk of the outcome is considered, often relative to the start and end dates of the target cohort.
**Model**: Defines the statistical model used to estimate the effect, including adjustments for time-varying confounders if necessary.

One of the SCCS design's strengths is its robustness to confounding by factors that differ between individuals, as each participant serves as their own control. However, it remains sensitive to time-varying confounding factors. To mitigate this, adjustments can be made for factors such as age, seasonality, and calendar time, enhancing the model's accuracy.

An advanced variant of the SCCS also considers all other drug exposures recorded in the database, significantly expanding the model's variables. This approach employs L1-regularization, with cross-validation used to select the regularization hyperparameter for all exposures except the one of interest.

An important assumption of the SCCS is that the observation period's end is independent of the outcome date. This may not hold true for outcomes that can be fatal, such as stroke. To address this, extensions to the SCCS model have been developed that correct for any dependency between the observation period end and the outcome.

# Features and Functionalities

The [SelfControlledCaseSeries](https://ohdsi.github.io/SelfControlledCaseSeries/ "SCCS") R package allows the user to perform SCCS analyses in an observational database in the OMOP Common Data Model. Some of the features offered by the SCCS module include:

1. **Data Extraction: Extracts necessary data from databases structured in the OMOP Common Data Model (CDM) format, ensuring uniformity and compatibility across diverse healthcare settings.
2. **Seasonality Adjustment**: Offers the option to adjust for seasonality effects using a spline function, enhancing the model's accuracy by accounting for seasonal variation in exposure and outcome rates.
3. **Age Adjustment**: Provides the option to incorporate age adjustments using a spline function, allowing for more nuanced analyses that consider the impact of age on the exposure-outcome relationship.
4. **Calendar Time Adjustment**: Enables the inclusion of calendar time adjustments using a spline function, addressing potential temporal trends in the data that could confound the exposure-outcome relationship.
5. **Event-dependent Censoring Correction**: Features the ability to correct for event-dependent censoring of the observation period, ensuring that the end of the observation period is appropriately handled, especially in cases where it might be related to the outcome.
6. **Comprehensive Covariate Inclusion**: Allows for the addition of a wide array of covariates in one analysis, such as all recorded drug exposures, facilitating a thorough examination of potential confounders and effect modifiers.
7. **Risk Window Customization**: Supports the construction of various types of covariates and risk windows, including pre-exposure windows, to capture contra-indications and other relevant temporal patterns related to exposure and outcome.
8. **Regularization of Covariates**: Applies regularization to all covariates except the outcome of interest, employing techniques like L1-regularization with cross-validation for selecting the regularization hyperparameter, thereby preventing overfitting and enhancing model reliability.
9. **Self-Controlled Risk Interval Design**: Incorporates the self-controlled risk interval design as a specific application of the SCCS method, offering additional methodological flexibility for studying short-term effects of exposures.
10.  **Power**: Incorporates power analysis techniques to estimate the statistical power of the study design, aiding in sample size determination and study planning, and provides a minimum-detectable relative risk (MDRR) statistic.
11.  **Attrition**:  Assesses attrition rates within cohorts, providing insights into potential biases introduced by data loss during the study period, and provides a visualization of attrition across various cohort criteria.
12. **Spanning**: Analyzes the number of subjects observed for 3 consecutive months, providing insights into the cohort's consistency and stability over time.
13. **Time Trend**: Assesses the ratio of observed to expected outcomes per month, with adjustments for calendar time, seasonality, and/or age as specified in the model, to examine time trends in the data.
14. **Time to Event**: Evaluates the number of events and subjects observed per week relative to the start of the first exposure, offering critical insights into the temporal relationship between exposure and outcome.
15. **Event-dependent Observation**: Provides histograms for the time between the first occurrence of the outcome and the end of observation, stratified by censored and uncensored ends of observation, to assess the impact of event-dependent observation periods.
16. **Systematic Error**: Assesses effect size estimates for negative controls (true hazard ratio = 1) and positive controls (true hazard ratio > 1) both before and after calibration. Estimates below the diagonal dashed lines are statistically significant (alpha = 0.05) different from the true effect size. A well-calibrated estimator should have the true effect size within the 95 percent confidence interval 95 percent of times, providing researchers with confidence in the reliability of the estimation process and the accuracy of the obtained results.

# Utility and Application

The SCCS method is particularly applicable in several key areas of epidemiological research and pharmacovigilance:

**Drug Safety Surveillance**: The SCCS method is widely used in drug safety surveillance to identify adverse effects of medications post-marketing. It is well-suited to detect short-term risks associated with drug exposures, especially where the onset of the adverse event is expected to be temporally close to the exposure.

**Vaccine Safety Evaluation**: The SCCS design is ideal for assessing the safety of vaccines, especially in evaluating the risk of adverse events following immunization. Its self-controlled nature helps to address concerns about confounding by indication and other biases that can affect observational studies in vaccine safety.

**Comparative Effectiveness Research**: While primarily designed for evaluating the safety of medical interventions, the SCCS method can also be adapted to compare the effectiveness of different treatments or interventions within the same individual over time, particularly for acute conditions.

**Epidemiological Research**: More broadly, the SCCS method is used in epidemiological research to study the temporal relationships between exposures and outcomes, offering insights into the causality and mechanisms underlying health conditions and diseases.
