---
  output: html_document
---
  
```{r, echo=FALSE, results='asis'}

getExternalVal <- function(
  connection,
  resultSchema,
  targetDialect,
  myTableAppend,
  modelDesignId,
  tempEmulationSchema = NULL
){
  
    sql <- "select per.performance_id, d.database_name as validation_database
      from 
      (select performance_id, validation_database_id from 
      @result_schema.@my_table_appendperformances 
      where model_design_id = @model_design_id 
      and development_database_id != validation_database_id) per
      inner join @result_schema.@my_table_appenddatabase_details d
      on d.database_id = per.validation_database_id;
    "
    sql <- SqlRender::render(
    sql = sql, 
    result_schema = resultSchema,
    my_table_append = myTableAppend,
    model_design_id = modelDesignId
  )
    
    sql <- SqlRender::translate(
    sql = sql, 
    targetDialect = targetDialect, 
    tempEmulationSchema = tempEmulationSchema
    )
  
  res <- DatabaseConnector::querySql(
    connection = connection, 
    sql = sql, 
    snakeCaseToCamelCase = T
    )
  if(is.null(res$performanceId) || length(res$performanceId)==0){
    return(NULL)
  }
  
  # get the performances for the performanceId
  result <- list()
  length(result) <- length(res$performanceId)
  
  for(i in 1:length(result)){
  result[[i]] <- list()
  tableNames <- c(
    'attrition', 
    'prediction_distribution',
    'covariate_summary',
    'threshold_summary',
    'calibration_summary',
    'evaluation_statistics',
    'demographic_summary'
    )
  length(result[[i]]) <- length(tableNames)+1
  names(result[[i]]) <- c('database',tableNames)
  result[[i]][['database']] <- res$validationDatabase[i]
  
  for(tabName in tableNames){
  
  sql <- "select * from 
    @result_schema.@my_table_append@table_name 
    where performance_id = @performance_id 
    "
    sql <- SqlRender::render(
    sql = sql, 
    result_schema = resultSchema,
    table_name = tabName,
    my_table_append = myTableAppend,
    performance_id = res$performanceId[i]
  )
    
    sql <- SqlRender::translate(
    sql = sql, 
    targetDialect = targetDialect, 
    tempEmulationSchema = tempEmulationSchema
    )
  
  result[[i]][[tabName]] <- DatabaseConnector::querySql(
    connection = connection, 
    sql = sql, 
    snakeCaseToCamelCase = T
    )
  }
  }
  
  return(result)
}

resultList <- getExternalVal(
  connection = params$connection,
  resultSchema = params$resultSchema,
  targetDialect = params$targetDialect,
  myTableAppend = params$myTableAppend,
  modelDesignId = params$modelDesignIds[i]
  )
```

## External Validation

The external validation is the performance of the models when validated using a new database.

```{r results='asis', echo=FALSE}
if(!is.null(resultList)){
  for (i in 1:length(resultList)) {
    result <- resultList[[i]]
    if(!is.null(result)){
      modelDesign <- knitr::knit_child(
        "plp-results-template.Rmd", 
        quiet = TRUE, 
        envir = environment()
        )
      cat(modelDesign, sep = '\n')
      }
    }
  } else{
    cat('\n No external validation available \n')
  }

```