---
  output: html_document
---

```{r results='asis', echo=FALSE}
cat('\n ',paste0('Validation on ', result$database), '\n')
```

#### Attrition

```{r results='asis', echo=FALSE}
result$attrition %>%
  dplyr::select(-"performanceId") %>%
  kableExtra::kbl() %>%
  kableExtra::kable_material_dark()
```

#### Summary

```{r results='asis', echo=FALSE}
result$evaluation_statistics %>%
  dplyr::select(-"performanceId") %>%
  tidyr::pivot_wider(
    id_cols =  "metric",  #.data$metric, 
    names_from = "evaluation", #.data$evaluation, 
    values_from = "value" #.data$value
    ) %>%
  kableExtra::kbl() %>%
  kableExtra::kable_material_dark()
```

#### Plots

add roc and smooth cal plots here
  
#### Covariates

```{r results='asis', echo=FALSE}
result$covariate_summary %>%
  dplyr::select(
    c(
    "covariateName", 
    "covariateValue",
    "covariateCount",
    "withNoOutcomeCovariateMean",
    "withOutcomeCovariateMean",
    "standardizedMeanDiff"
    )
    ) %>%
  kableExtra::kbl() %>%
  kableExtra::kable_material_dark()
```
  