

#' Creating a list of custom column definitions for use in reactables
#'
#' @param rawColNames The raw column names taken directly from the source
#'  data table that are to be overwritten in the reactable
#' @param niceColNames The formatted column names that will appear as-specified in 
#' the reactable
#' @param tooltipText The text to be displayed in a toolTip when hovering over the 
#' column in the reactable
#'
#' @return A named list of reactable::colDef objects
#' @export
#'
#' @examples
#' createCustomColDefList(rawColNames = c("firstName", "lastName), niceColNames = c("First Name", "Last Name"), tooltipText = c("The person's first name", "The person's last name"))
#' 
createCustomColDefList <- function(rawColNames, niceColNames, tooltipText) {
  withTooltip <- function(value, tooltip, ...) {
    shiny::div(style = "text-decoration: underline; text-decoration-style: dotted; cursor: help",
               tippy::tippy(value, tooltip, ...))
  }
  
  result <- vector("list", length(rawColNames))
  
  for (i in 1:length(rawColNames)) {
    result[[i]] <- reactable::colDef(
      header = withTooltip(niceColNames[[i]], tooltipText[[i]])
    )
  }
  
  names(result) <- rawColNames
  
  return(result)
}



#' Saving a custom colDef list to a JSON file
#'
#' @param colDefs A named list of reactable::colDef objects, generated by createCustomColDefList()
#' @param filename The desired name of the output JSON file
#' @param path The path to where the JSON should be saved
#'
#' @return Saves a JSON file
#' @export 
#'
# saveColDefsAsJSON <- function(colDefs, filename, path = "") {
#   # Extract the raw column names
#   raw_col_names <- names(colDefs)
#   
#   # Convert colDefs to a named list with "header" field
#   col_defs_list <- lapply(colDefs, function(colDef) list(header = as.character(colDef$header)))
#   
#   # Create a named list with raw column names and colDefs list
#   col_defs_json <- jsonlite::toJSON(setNames(col_defs_list, raw_col_names))
#   
#   # Write JSON to file
#   filepath <- file.path(path, filename)
#   writeLines(col_defs_json, filepath)
# }

saveColDefsAsJSON <- function(colDefs, filename, path = "") {
  # Convert colDefs to a list of serializable objects
  colDefsData <- lapply(colDefs, function(colDef) list(header = as.character(colDef$header)))
  
  # Convert the list to JSON
  colDefsJson <- jsonlite::toJSON(colDefsData, auto_unbox = TRUE)
  
  # Construct the file path
  filepath <- file.path(path, filename)
  
  # Write JSON to file
  writeLines(colDefsJson, filepath)
}







#' Read reactable::colDefs froma  JSON file 
#'
#' @param filename The dname of the input JSON file
#' @param path The path to where the JSON is located
#'
#' @return
#' @expors Reads in a JSON file and saves it into the environment as a named list of colDefs
#'
readColDefsFromJSON <- function(filename, path = "") {
  # Construct the file path
  filepath <- file.path(path, filename)
  
  # Read JSON from file
  colDefsJson <- readLines(filepath)
  
  # Convert JSON to list
  colDefsData <- jsonlite::fromJSON(colDefsJson, simplifyVector = FALSE)
  
  # Convert list elements to colDef objects
  colDefs <- lapply(colDefsData, function(data) {
    header <- shiny::tags$div(
      style = "text-decoration: underline; text-decoration-style: dotted; cursor: help",
      shiny::tags$span(class = "tippy html-widget html-fill-item-overflow-hidden html-fill-item", 
                       id = "htmlwidget-989018cda6e9bce08b15", width = "960",
                       data = jsonlite::toJSON(list(x = list(opts = list(content = data$header),
                                                             text = data$header),
                                                    evals = list(),
                                                    jsHooks = list())),
                       height = "500"),
      shiny::tags$script(type = "application/json", 
                         data_for = "htmlwidget-989018cda6e9bce08b15",
                         jsonlite::toJSON(list(x = list(opts = list(content = data$header),
                                                        text = data$header),
                                               evals = list(),
                                               jsHooks = list()))))
    
    reactable::colDef(header = header)
  })
  
  return(colDefs)
}







#examples

# createCustomColDefList(rawColNames = c("firstName", "lastName"),
#                        niceColNames = c("First Name", "Last Name"),
#                        tooltipText = c("The person's first name", "The person's last name"))

# Sample data
# rawColNames <- c("col1", "col2", "col3")
# niceColNames <- c("Column 1", "Column 2", "Column 3")
# tooltipText <- c("Tooltip 1", "Tooltip 2", "Tooltip 3")
# 
# # Call the function
# colDefs <- createCustomColDefList(rawColNames, niceColNames, tooltipText)
# 
# # Save colDefs as JSON in a specific path
# saveColDefsAsJSON(phevalColList, "phevaluator-colDefs.json", path = "D:/shiny_test/GitHub Desktop/standardization/OhdsiShinyModules/inst/components-columnInformation")

# testing <- readColDefsFromJSON("phevaluator-colDefs.json", "D:/shiny_test/GitHub Desktop/standardization/OhdsiShinyModules/inst/components-columnInformation")